### ISSUE TITLE
Possible issue if Discord rebuilds their web app

### ISSUE THREAD

**Issue by BE-CH** [yannhodiesne/Discord-M1#11]
https://github.com/yannhodiesne/Discord-M1/blob/b5684e365f12cb1de057fb1a63bf90ad5c440052/discord-badge-count.js#L12

Lines such as the one above might break, if Discord rebuilds their application.
This is due to the Discord web app being built using React (and webpack) and therefore the last part (``1Bvpku`` and ``2hkk8m``) of the classnames might change next build.

Anyone that can confirm this?

**Comment by yannhodiesne** [comment]
It could be an issue, but it seems they are not rebuilding their entire app on every update as these classnames has been in use for more than one year  
We might need to update them when they release breaking changes, but I did not find a way to make our feature-set compatible with all languages without using these classnames
