### ISSUE TITLE
Discord crashed after updating to #1.6.1

### ISSUE THREAD

**Issue by dyanakiev** [yannhodiesne/Discord-M1#12]
Discord crashed after updating to #v1.6.1 and launching from Applications folder.

![SCR-20211102-r69](https://user-images.githubusercontent.com/11967079/139916677-0799fa49-8e36-4cf1-bf5e-450806ba2316.png)

Note: This happened just once, now its working.

**Comment by dyanakiev** [comment]
Mine just crashed again after receiving notification in background

**Comment by yannhodiesne** [comment]
> 
> 
> Mine just crashed again after receiving notification in background

I could not reproduce it on my mac, could you open the developer tools inside Discord and copy/paste the console logs inside a pastebin and post it there the next time it happens ?

**Comment by codepope** [comment]
Same thing here. Sorry no logs.

**Comment by SoloUnity** [comment]
> > Mine just crashed again after receiving notification in background
> 
> I could not reproduce it on my mac, could you open the developer tools inside Discord and copy/paste the console logs inside a pastebin and post it there the next time it happens ?

Discord crashed when I got a notification while I was browsing on another app. 
This is the error I'm getting in the console:

DevTools failed to load source map: Could not load content for https://discord.com/assets/c7a28c9b69ea20a48f6b.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/c776b9baf3700c876770.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/8e6c16fdfb58abab6be5.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/bab22e015568b17385c0.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/1d900604a01a0fbd9fc5.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/11038da16ee9b738c59c.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/48bf519c6e7e8afa56bb.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/b244897e78d949d00f7d.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/8d6146314ec20f9462f2.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/68983a641f08eb6dba0d.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/5d770e28c922e85bc568.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/b0a2220f8f52816b8f6f.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/652fc96337a456bd460d.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/69849aa362126d063ca6.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/8200fcd754afd6d7dbe4.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/5cf9e4e596b05bfd6ca7.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/9cff165286cd4fba1ac4.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/c9163337434ffe8260d1.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/1cf36a88672ec4dfe966.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/83259a4ad68f10026646.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/e2af2e77fa0cd11a3961.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/ca43344021180f8e3080.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/87baa88511bc28570c2c.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/7b672f5690c7f2e92e9d.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/1355d3d03c7068e2af61.worker.js.map: Fetch through target failed: Target not supported; Fallback: Unknown error
DevTools failed to load source map: Could not load content for https://discord.com/assets/d79244cd81582046c24f.worker.js.map: Fetch through target failed: Target not supported; Fallback: Unknown error
3DevTools failed to load source map: Could not load content for https://discord.com/assets/1355d3d03c7068e2af61.worker.js.map: Fetch through target failed: Target not supported; Fallback: Unknown error
DevTools failed to load source map: Could not load content for https://discord.com/assets/532.12fc18c8e0af7fef85cb.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by yannhodiesne** [comment]
I managed to get it crash to get the logs :
<details>
<summary>Crash logs</summary>
1777bb820649621c6f44.js:130 DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at Cs (https://discord.com/assets/0f7845e8bf9abd890fc9.js:5988:710)
    at Cs (https://discord.com/assets/0f7845e8bf9abd890fc9.js:5988:783)
    at Cs (https://discord.com/assets/0f7845e8bf9abd890fc9.js:5988:783)
    at Cs (https://discord.com/assets/0f7845e8bf9abd890fc9.js:5988:783)
    at Rs (https://discord.com/assets/0f7845e8bf9abd890fc9.js:5988:221)
    at Bu (https://discord.com/assets/0f7845e8bf9abd890fc9.js:6001:570)
    at t.unstable_runWithPriority (https://discord.com/assets/0f7845e8bf9abd890fc9.js:6239:828)
    at Ki (https://discord.com/assets/0f7845e8bf9abd890fc9.js:5940:117)
    at Vu (https://discord.com/assets/0f7845e8bf9abd890fc9.js:5999:668)
    at Au (https://discord.com/assets/0f7845e8bf9abd890fc9.js:5995:382)
    at https://discord.com/assets/0f7845e8bf9abd890fc9.js:5940:340
    at t.unstable_runWithPriority (https://discord.com/assets/0f7845e8bf9abd890fc9.js:6239:828)
    at Ki (https://discord.com/assets/0f7845e8bf9abd890fc9.js:5940:117)
    at Xi (https://discord.com/assets/0f7845e8bf9abd890fc9.js:5940:285)
    at qi (https://discord.com/assets/0f7845e8bf9abd890fc9.js:5940:220)
    at Ou (https://discord.com/assets/0f7845e8bf9abd890fc9.js:5995:485)
    at Function.e.emitChanges (https://discord.com/assets/0f7845e8bf9abd890fc9.js:4011:345)
    at e.t._dispatch (https://discord.com/assets/0f7845e8bf9abd890fc9.js:4000:229)
    at e.t.dispatch (https://discord.com/assets/0f7845e8bf9abd890fc9.js:3999:582)
    at e.t.dirtyDispatch (https://discord.com/assets/0f7845e8bf9abd890fc9.js:3999:541)
    at t.<anonymous> (https://discord.com/assets/0f7845e8bf9abd890fc9.js:2798:28)
    at t.a.emit (https://discord.com/assets/0f7845e8bf9abd890fc9.js:4883:915)
    at t.n._handleDispatch (https://discord.com/assets/0f7845e8bf9abd890fc9.js:1720:697)
    at https://discord.com/assets/0f7845e8bf9abd890fc9.js:1718:860
    at r._onDataReady (https://discord.com/assets/0f7845e8bf9abd890fc9.js:1718:340)
    at r.l.push.t.handleFlushEnd (https://discord.com/assets/0f7845e8bf9abd890fc9.js:1709:251)
    at d.push (https://discord.com/assets/0f7845e8bf9abd890fc9.js:5683:720)
    at r.l.push.t.feed (https://discord.com/assets/0f7845e8bf9abd890fc9.js:1708:662)
    at WebSocket.<anonymous> (https://discord.com/assets/0f7845e8bf9abd890fc9.js:1718:405)
</details>

I'm currently pushing an experimental fix to try and see if we still get those crashes

**Comment by SoloUnity** [comment]
> > Mine just crashed again after receiving notification in background
> 
> I could not reproduce it on my mac, could you open the developer tools inside Discord and copy/paste the console logs inside a pastebin and post it there the next time it happens ?

Here's what I got after getting a notification in the background while browsing another app:

https://pastebin.com/4vdYASZT

**Comment by yannhodiesne** [comment]
> > > Mine just crashed again after receiving notification in background
> > 
> > 
> > I could not reproduce it on my mac, could you open the developer tools inside Discord and copy/paste the console logs inside a pastebin and post it there the next time it happens ?
> 
> Here's what I got after getting a notification in the background while browsing another app:
> 
> https://pastebin.com/4vdYASZT

Thanks! These errors are actually Electron complaining about Discord not providing the map files, useful to debug their code, so they are not related to this issue

**Comment by yannhodiesne** [comment]
Just released version 1.6.2 with an attempt to fix these crashes
If you want to update, you can quit Discord entirely (by right clicking on it in your dock) and launch it again to trigger an update check

I'll let this issue open for a few days to confirm these crashes does not happen anymore
