### ISSUE TITLE
Window controls and sidebar overlaid on 1.6.1

### ISSUE THREAD

**Issue by codepope** [yannhodiesne/Discord-M1#14]
Here's what I see... so far restarting hasn't made it go away.

<img width="101" alt="Screenshot 2021-11-02 at 19 49 25" src="https://user-images.githubusercontent.com/72684/139942311-b5b15c04-7fe3-42ae-9d24-4e6cb8d2db2e.png">

And then literally as I'm typing this and having left it running in the background, it sorts itself out. Weird.

**Comment by BE-CH** [comment]
Fixed in PR https://github.com/yannhodiesne/Discord-M1/pull/17#issuecomment-961148024
