### ISSUE TITLE
Download apps icon not hidden (after 1.6.2)

### ISSUE THREAD

**Issue by BE-CH** [yannhodiesne/Discord-M1#15]
Just updated to the latest version, and now the download apps icon is no longer hidden.

I checked out the code its a fairly easy fix. We just need to
```
style="display:none;"
```
instead of just the ``hidden``.
https://github.com/yannhodiesne/Discord-M1/blob/2d2c108eb595270a28f4c5845173a0a89688a2c1/discord-downloadapps-icon.js#L60

Furthermore, now that we only hide them we need to implement another way to stop searching when we have found and hidden the elements. 

I can take a look at it tomorrow and provide a PR with a fix.

**Comment by yannhodiesne** [comment]
> Just updated to the latest version, and now the download apps icon is no longer hidden.

I noticed the regression too, but I was in a hurry and did not want to keep a crashing build as the latest release for too long

> I can take a look at it tomorrow and provide a PR with a fix.

It would be awesome!

**Comment by BE-CH** [comment]
> > Just updated to the latest version, and now the download apps icon is no longer hidden.
> 
> I noticed the regression too, but I was in a hurry and did not want to keep a crashing build as the latest release for too long
> 
> > I can take a look at it tomorrow and provide a PR with a fix.
> 
> It would be awesome!

Fixed in PR #17
