### ISSUE TITLE
Discord accepts CMD+R despite not being active window

### ISSUE THREAD

**Issue by Chew** [yannhodiesne/Discord-M1#19]
If I CMD+R anywhere, for example, this very browser, it reloads Discord, not the browser. This prevents me from reloading via keybind since it simply reloads the client that isn't even focused.

Is there a way to make Discord ignore the reload keybind if it's not focused?

**Comment by robbiet480** [comment]
This just started happening as of this mornings update.

**Comment by robbiet480** [comment]
@BE-CH looks like this was introduced by #17

**Comment by robbiet480** [comment]
@yannhodiesne Probably best to revert #17 and pull 1.6.8 for now...

**Comment by robbiet480** [comment]
Thanks for the quick fix @yannhodiesne!

**Comment by Chew** [comment]
Thank ya! Back to using this. It boots 5x faster so it's truly a no-brainer lol. Now only if it were canary without me having to do `window.location.href = "https://canary.discord.com/app"` 😢

**Comment by yannhodiesne** [comment]
> Thank ya! Back to using this. It boots 5x faster so it's truly a no-brainer lol. Now only if it were canary without me having to do `window.location.href = "https://canary.discord.com/app"` 😢

You might want to create a separate issue for this feature, I can try to add a switch to toggle between stable and canary when I've got more time
I probably won't have the time to fix bugs happening on canary, but I won't prevent anyone from using it
