### ISSUE TITLE
Allow option to switch to Canary/PTB

### ISSUE THREAD

**Issue by Chew** [yannhodiesne/Discord-M1#20]
A nice way to switch to an unsupported Canary/PTB would be nice. It may actually be a nifty way to have "alts" if you log in to 3 different accounts.

I'm not entirely sure how Electron works, but may it be possible to have it under one of the menu options? Like Window -> Switch to Canary or something? That's the easiest I can think of 😄

**Comment by yannhodiesne** [comment]
Fixed in https://github.com/yannhodiesne/Discord-M1/commit/14752fd0a903088fe894398bffcda88ba3bcbe59, will be released with version 1.7.0
Thank you for your contribution!
