### ISSUE TITLE
Screen-Sharing does not with in v1.7

### ISSUE THREAD

**Issue by Hye-Dev** [yannhodiesne/Discord-M1#23]
Screeensharing just gets stuck on loading after updating to v1.7

**Comment by yannhodiesne** [comment]
Could you elaborate, or send a screencast of the issue?

**Comment by Hasuuka** [comment]
Hey I have a similar problem. After activating screenshare system preferences opens up. I gave Discord permission to record the  screen. It restarted. After activating screen share the whole process starts again and system preferences opens up again

**Comment by yannhodiesne** [comment]
> Hey I have a similar problem. After activating screenshare system preferences opens up. I gave Discord permission to record the screen. It restarted. After activating screen share the whole process starts again and system preferences opens up again

Did you check you gave the permission to Discord-M1, and not the official client? I've seen macOS getting confused on my machine when switching between one and the other
Maybe removing Discord from the list and adding it again will do the trick

**Comment by Hasuuka** [comment]
I found a fix. Resetting the privacy rights after a Discord clean install helps.

- sudo tccutil reset ScreenCapture
- sudo tccutil reset Camera
- sudo tccutil reset Microphone

**Comment by yannhodiesne** [comment]
> I found a fix. Resetting the privacy rights after a Discord clean install helps.
> 
>     * sudo tccutil reset ScreenCapture
> 
>     * sudo tccutil reset Camera
> 
>     * sudo tccutil reset Microphone

Thanks for the workaround, I added it to the README

@Hye-Dev is this issue still relevent?

**Comment by yannhodiesne** [comment]
Closing the issue as the original poster did not provide enough information
