### ISSUE TITLE
Discord profile status changes to Idle when i'm actually using my computer

### ISSUE THREAD

**Issue by dyanakiev** [yannhodiesne/Discord-M1#24]
Hello i noticed that Discord profile status changes to Idle when i'm actually using my computer

**Comment by BE-CH** [comment]
> Hello i noticed that Discord profile status changes to Idle when i'm actually using my computer

If I have time, I will do a PR with a fix for this. If someone wants to do it before me, you can use the documentation below;

PowerMonitor - to check computer state with Electron: https://www.electronjs.org/docs/latest/api/power-monitor#powermonitorgetsystemidlestateidlethreshold

**Comment by dyanakiev** [comment]
closing, no longer issue with the native discord m1 app
