### ISSUE TITLE
Allow switching to Canary and PTB

### ISSUE THREAD

**Issue by robbiet480** [yannhodiesne/Discord-M1#25]
As per @Chew’s request in #19, can a toggle be added to allow switching to PTB and Canary apps?

**Comment by yannhodiesne** [comment]
The feature is already there, check in your menu bar: Discord > Switch to another channel

**Comment by Chew** [comment]
Yep I use it and love it:

![image](https://user-images.githubusercontent.com/8278263/140805091-2c4753a6-f8be-45d0-8801-068bf9b28ff3.png)
