### ISSUE TITLE
Play/Pause issue

### ISSUE THREAD

**Issue by tommasobenatti** [yannhodiesne/Discord-M1#28]
After using the client for a while the play/pause key stops working untill I restart discord, this "bug" is system wide

**Comment by tommasobenatti** [comment]
By system wide I mean that on the browser or Spotify if I try to use the Play/Pause button on a external keyboard/touch bar nothing happens, but if I restart the discord client it starts working again

**Comment by yannhodiesne** [comment]
That's a weird issue, I did not encounter it yet
Did you play any media inside of Discord by any chance? Maybe Electron is registering itself as a media player when you watch an embedded video

**Comment by tommasobenatti** [comment]
Yes, I can confirm, it happens after I play a video inside discord and changing channel, it looks like Electron keeps using the play/pause button, you can try it too, is very easy to reproduce

**Comment by yannhodiesne** [comment]
Fixed in v1.7.1 🎉

**Comment by tommasobenatti** [comment]
thanks, I'll try

**Comment by tommasobenatti** [comment]
yep, fixed, thanks
