### ISSUE TITLE
Cannot share screen

### ISSUE THREAD

**Issue by kostrykin** [yannhodiesne/Discord-M1#30]
I cannot share my screen. When I try, the settings window for security and privacy opens, where I am probably supposed to grant access for screen sharing. However, the app isn't listed there.
<img width="789" alt="Bildschirmfoto 2021-11-12 um 13 04 41" src="https://user-images.githubusercontent.com/6557139/141464477-b4d50e8f-0b9a-4366-8f02-4899987f21f9.png">

**Comment by SoloUnity** [comment]
Click the plus and add it manually

**Comment by akswalia23** [comment]
I have done this, and reset as well still with it opening system preferences?
