### ISSUE TITLE
Audio live not working

### ISSUE THREAD

**Issue by tommasobenatti** [yannhodiesne/Discord-M1#32]
When I'm doing a live of an app it doesn't stream the sound

**Comment by laurazard** [comment]
I don't think that's going to be easy to support until Discord themselves support M1 -- in the official app, on macOS, to capture sound while screen capturing it's required to install a helper application. This application is based on the web version of discord, which also does not support audio capture.

**Comment by tommasobenatti** [comment]
Ok, thank you anyway, i'll close this
