### ISSUE TITLE
The screen sharing popout is opening in an external browser

### ISSUE THREAD

**Issue by yannhodiesne** [yannhodiesne/Discord-M1#5]
When watching a screen share, Discord has a button to open it inside a second window  
Right now, clicking on it only opens an empty tab inside the system's default browser

**Comment by imabhaysutar** [comment]
Heyy, would like to point out that this same behaviour applies to video pop out option. 

Thanks for the app!!!

**Comment by imabhaysutar** [comment]
thanks a lot!! this seems to work great.
