### ISSUE TITLE
Hide download apps icon

### ISSUE THREAD

**Issue by h2flux** [yannhodiesne/Discord-M1#6]
<img width="69" alt="image" src="https://user-images.githubusercontent.com/91643698/139121937-69fea6db-11da-49d5-8e60-92a98716fca4.png">

Excuse my ignorance on the subject; I don't know if this would be possible or not. It would be cool however, to be able to hide this icon to make it feel more like an official app.

**Comment by BE-CH** [comment]
I made a PR for this. Link: #10

**Comment by BE-CH** [comment]
@yannhodiesne Possible to get my PR merged?

**Comment by yannhodiesne** [comment]
Fixed by @BE-CH in #10 and released with version 1.6.1 : https://github.com/yannhodiesne/Discord-M1/releases/tag/v1.6.1
