### ISSUE TITLE
Documentation update: Screen Sharing works if added manually

### ISSUE THREAD

**Issue by RickyRomero** [yannhodiesne/Discord-M1#8]
Hey, quick note here. The documentation says that screen sharing doesn't work if you move Discord-M1 into /Applications. However, I put Discord-M1 in /Applications and was able to get the screen recording permission working just fine on macOS Monterey (21A559).

Here's how I did it:

1. Move Discord.app into /Applications, clear the quarantine flag, launch it, etc.
1. Open System Preferences > Security & Privacy > Privacy > Screen Recording
1. Manually drag Discord into the list of screen recording apps.
1. Restart the app if it's still running.

I haven't tested this method on Big Sur, but it totally works on Monterey!

**Comment by yannhodiesne** [comment]
Thanks for your feedback !  
Last time I tried to add the permission manually with the app in the Applications folder, macOS ignored it and Discord was still not able to share my screen  
We might need to check your workaround on several environments to ensure it works for everyone, to avoid confusion for non-tech savvy users 

I'll give it a try on my Mac later this week and try to find a friend or two to test it too, it would be great to be able to put it inside the Applications folder !

**Comment by yannhodiesne** [comment]
Fixed in version 1.6.1 as the application is now signed :)
https://github.com/yannhodiesne/Discord-M1/releases/tag/v1.6.1

**Comment by RickyRomero** [comment]
An even better outcome! Thank you! 🎉
