### ISSUE TITLE
Would it be possible to sign the application?

### ISSUE THREAD

**Issue by BE-CH** [yannhodiesne/Discord-M1#9]
As stated in the README, this application is not signed by Apple because you "did not pay Apple's 99$ fee to sign the application".

### **Would it even be possible for this application to be signed?**
If so, I am willing to donate towards this goal.

**Comment by yannhodiesne** [comment]
Yes it is indeed possible! In fact, I bought a developer license this weekend and will release the first signed binary once your PR (#10) has been merged.
It will remove the need for installation workarounds and allow automatic updates on launch, which is a huge step forward for this project!

From a personal standpoint, I am not willing to accept any kind of donation that I could personally benefit from. Nonetheless, thank you very much for your offer!
